## ================= Elastic Connectors Configuration ==================
elasticsearch:
  api_key: "TENHc0NJb0JUenpGcm1hdHAwVW06ODlndFRkaUhTTGU4dEtEZVZ5RlNLZw=="
  connector_id: "XnOsCIoBtQo9WzNoSckJ"
  service_type: "google_cloud_storage"
